### ISSUE TITLE
build bug

### ISSUE THREAD

**Issue by ArtificialZeng** [kungfu-origin/kungfu#105]
[4/4] Building fresh packages...
[-/6] ⠁ waiting...
[-/6] ⠁ waiting...
[3/6] ⠂ electron
[-/6] ⠂ waiting...
error /mnt/d/GoogleDownload/kungfu-2.1/kungfu-2.1/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /mnt/d/GoogleDownload/kungfu-2.1/kungfu-2.1/node_modules/electron
Output:
Downloading tmp-6456-0-electron-v4.2.11-linux-x64.zip
Error: connect ETIMEDOUT 20.205.243.166:443
/mnt/d/GoogleDownload/kungfu-2.1/kungfu-2.1/node_modules/electron/install.js:49
  throw err
  ^

**Comment by ArtificialZeng** [comment]
[4/4] Building fresh packages...
$ yarn wsrun --serial install-deps && npm config set kungfu-core:runtime electron
yarn run v1.22.19
$ /root/kungfu/node_modules/.bin/wsrun --serial install-deps
kungfu-core
$ cross-env PIPENV_TIMEOUT=600 pipenv --three install
 | events.js:174
 |       throw er; // Unhandled 'error' event
 |       ^
 | 
 | Error: spawn pipenv ENOENT
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     at process._tickCallback (internal/process/next_tick.js:63:19)
 |     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
 |     at startup (internal/bootstrap/node.js:283:19)
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 | Emitted 'error' event at:
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     [... lines matching original stack trace ...]
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn install-deps` failed with exit code 1
kungfu
$ electron-builder install-app-deps
 |   • electron-builder  version=21.2.0
 |   • loaded configuration  file=package.json ("build" field)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@container-fed111b7ac-72dc9967:~/kungfu# yarn
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ yarn wsrun --serial install-deps && npm config set kungfu-core:runtime electron
yarn run v1.22.19
$ /root/kungfu/node_modules/.bin/wsrun --serial install-deps
kungfu-core
$ cross-env PIPENV_TIMEOUT=600 pipenv --three install
 | events.js:174
 |       throw er; // Unhandled 'error' event
 |       ^
 | 
 | Error: spawn pipenv ENOENT
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     at process._tickCallback (internal/process/next_tick.js:63:19)
 |     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
 |     at startup (internal/bootstrap/node.js:283:19)
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 | Emitted 'error' event at:
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     [... lines matching original stack trace ...]
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn install-deps` failed with exit code 1
kungfu
$ electron-builder install-app-deps
 |   • electron-builder  version=21.2.0
 |   • loaded configuration  file=package.json ("build" field)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@container-fed111b7ac-72dc9967:~/kungfu# yarn
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ yarn wsrun --serial install-deps && npm config set kungfu-core:runtime electron
yarn run v1.22.19
$ /root/kungfu/node_modules/.bin/wsrun --serial install-deps
kungfu-core
$ cross-env PIPENV_TIMEOUT=600 pipenv --three install
 | events.js:174
 |       throw er; // Unhandled 'error' event
 |       ^
 | 
 | Error: spawn pipenv ENOENT
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     at process._tickCallback (internal/process/next_tick.js:63:19)
 |     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
 |     at startup (internal/bootstrap/node.js:283:19)
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 | Emitted 'error' event at:
 |     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
 |     at onErrorNT (internal/child_process.js:415:16)
 |     [... lines matching original stack trace ...]
 |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn install-deps` failed with exit code 1
kungfu
$ electron-builder install-app-deps
 |   • electron-builder  version=21.2.0
 |   • loaded configuration  file=package.json ("build" field)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@container-fed111b7ac-72dc9967:~/kungfu#
