### ISSUE TITLE
Can't compile at CentOS 7.8

### ISSUE THREAD

**Issue by tekpig** [kungfu-origin/kungfu#70]
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn wsrun --serial install-deps && npm config set kungfu-core:runtime electron
yarn run v1.22.10
$ /home/zhech/Works/kungfu/node_modules/.bin/wsrun --serial install-deps
kungfu-core
$ cross-env PIPENV_TIMEOUT=600 pipenv --three install
 | Virtualenv already exists!
 | Removing existing virtualenv...
 | Creating a virtualenv for this project...
 | Pipfile: /home/zhech/Works/kungfu/core/Pipfile
 | Using /usr/bin/python3.6m (3.6.8) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.6.8.final.0-64 in 371ms
 |   creator CPython3Posix(dest=/home/zhech/.local/share/virtualenvs/core-xouqbSRt, clear=False, global=False)
 |   seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/zhech/.local/share/virtualenv)
 |     added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
 |   activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
 | 
 |✔ Successfully created virtual environment! 
 | Virtualenv location: /home/zhech/.local/share/virtualenvs/core-xouqbSRt
 | Virtualenv already exists!
 | Removing existing virtualenv...
 | Creating a virtualenv for this project...
 | Pipfile: /home/zhech/Works/kungfu/core/Pipfile
 | Using /usr/bin/python3.6m (3.6.8) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.6.8.final.0-64 in 233ms
 |   creator CPython3Posix(dest=/home/zhech/.local/share/virtualenvs/core-xouqbSRt, clear=False, global=False)
 |   seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/zhech/.local/share/virtualenv)
 |     added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
 |   activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
 | 
 |✔ Successfully created virtual environment! 
 | Virtualenv location: /home/zhech/.local/share/virtualenvs/core-xouqbSRt
 | Pipfile.lock not found, creating...
 | Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
⠴ Locking..✔ Success! 
 | Locking [packages] dependencies...
⠋ Locking...Building requirements...
Resolving dependencies...
⠙ Locking..✘ Locking Failed! 
 | Traceback (most recent call last):
 |   File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 763, in <module>
 |     main()
 |   File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 759, in main
 |     parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
 |   File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 741, in _main
 |     resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
 |   File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
 |     requirements_dir=requirements_dir,
 |   File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 692, in resolve
 |     req_dir=requirements_dir
 |   File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 1386, in resolve_deps
 |     req_dir=req_dir,
 |   File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 1091, in actually_resolve_deps
 |     deps, index_lookup, markers_lookup, project, sources, req_dir, clear, pre
 |   File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 649, in create
 |     pre=pre, clear=clear
 |   File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 463, in get_metadata
 |     req, resolver=transient_resolver
 |   File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 610, in get_deps_from_req
 |     best_match = pypi.find_best_match(req.ireq) if pypi else None
 |   File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
 |     raise NoCandidateFound(ireq, all_candidates, self.finder)
 | pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches pywin32==227
 | No versions found
 | Was http://mirrors.aliyun.com/pypi/simple/ reachable?
 | 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn install-deps` failed with exit code 1
kungfu
$ electron-builder install-app-deps
 |   • electron-builder  version=21.2.0
 |   • loaded configuration  file=package.json ("build" field)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

My Python version is 2.7.5, Python3 version is 3.6.8

**Comment by tekpig** [comment]
I have tried to change aliyun to tuna.tsinghua, but it still doesn't work.
